# Generated by Django 5.0.1 on 2024-01-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
